### ISSUE TITLE
enhancement(Music): Seek in resume and pause

### ISSUE THREAD

**Issue by kyranet** [skyra-project/skyra.pw#156]
When clicking on "pause" or "resume", the action comes delayed on slow internet, the events could come with some seek data so they resume or pause at the right position.

**Comment by Favna** [comment]
Denying this because it is an unrealistic request. We can build in a delay but there's going to be people with a 10000ms ping to Germany and then a delay still won't do anything. It's unrealistic to provide for people with slow internet.
