### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by gc** [skyra-project/skyra.pw#26]
This issue is a mega-issue for any bugs/issues found. Comment if you find one not here.

**General Bugs**
- ~~Single-value keys (like roles or channels) cannot be set to unset.~~
- Changing a setting, then reverting it back so theres no changes still leaves the FAB's up
- ~~@everyone role is an option when picking public roles~~

**Mobile Bugs**
- ~~Close sidebar on click~~
- ~~Hide Breadcrumbs in appbar, show only guild name?~~
- ~~make dashboard form items wrap (see: language on index page)~~

**Comment by kyranet** [comment]
- Single-value keys (like roles or channels) cannot be set to unset.

**Comment by gc** [comment]
Change "Not in server" text to something like "Click to invite Skyra to this server"

**Comment by gc** [comment]
Fix footer to actually be links, and @kyranet  do you have more links we could add to make it symmetrical?

**Comment by Favna** [comment]
Fix flexbox height issues on iOS / Samsung Web Browser / MacOS Safari

**Comment by gc** [comment]
Fill out real text on the homepage

**Comment by gc** [comment]
Fix color of scrollbar

**Comment by gc** [comment]
Make GeneralPage logo clickable to homepage

**Comment by gc** [comment]
Add links in header

**Comment by gc** [comment]
Filter pages: Hide duration if no action selected, and if duration isn't applicable to the action

**Comment by kyranet** [comment]
SelectDuration: Reset button (sets to null)

**Comment by Favna** [comment]
Words filter should display "words" at the top ![image](https://user-images.githubusercontent.com/4019718/69937933-43bc5c80-14dc-11ea-82c9-c5544570c415.jpg)

---

Action drop-down should have the same style as the other two
![image](https://user-images.githubusercontent.com/4019718/69937950-4dde5b00-14dc-11ea-8070-ebe1811a1558.jpg)

**Comment by gc** [comment]
if the user sync returns 401 then force log out

**Comment by gc** [comment]
![image](https://user-images.githubusercontent.com/30398469/69951102-bbc06c00-1548-11ea-8f43-23dae7a01fc6.png)
this

**Comment by kyranet** [comment]
[Lighthouse:a11y] Background and foreground colors do not have a sufficient contrast ratio:

![image](https://user-images.githubusercontent.com/24852502/69951995-99056780-14f6-11ea-970f-97b9e20654e6.png)

**Comment by kyranet** [comment]
[Lighthouse:SEO] Tap targets are not sized appropriately:

![image](https://user-images.githubusercontent.com/24852502/69952203-f8fc0e00-14f6-11ea-857b-8675ff3ceda6.png)

**Comment by kyranet** [comment]
[Lighthouse:Performance]: Serve images in next-gen formats & Properly size images:

![image](https://user-images.githubusercontent.com/24852502/69952347-49736b80-14f7-11ea-860c-fd70e3d99610.png)

**Comment by kyranet** [comment]
Icon-less guilds cause 404 errors in console, it should show the letters instead.

![image](https://user-images.githubusercontent.com/24852502/69956514-7bd59680-1500-11ea-9409-fedf8bc7ab44.png)

**Comment by gc** [comment]
Sort channels and roles as they are in the server

**Comment by Favna** [comment]
Incorrect units are displayed in the error of the textfield. Tried to fix it but the whole determining of units is voodoo magic to me @gc .

![image](https://user-images.githubusercontent.com/4019718/72225083-89f7e780-3581-11ea-85c6-652fb8f8fce0.png)
